#
#

name: build_and_test_from_pkg

on:
  push:
    branches: [feat]
  pull_request:
    branches: [main]
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build and test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build pytest
          python -m pip install torch torchvision

      - name: Build project
        run: python -m build

      - name: Install built package
        run: pip install dist/*.whl # only works in bash/linux

        # $whl = Get-ChildItem -Path dist\*.whl | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        # pip install $whl

      - name: Run tests with pytest
        run: pytest test/test_build_under_vev.py