#
#

name: build_and_test_from_pkg

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build and test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest
          python -m pip install torch torchvision

      - name: Build project
        run: python -m build

      - name: Install built package
        run: pip install dist/*.whl

      - name: Run tests with pytest
        run: pytest test/test_build_under_vev.py