
name: Build_Package

on:
  push:
    branches:
      - feat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up cache for pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-    

      - name: get the wd
        run: pwd  

      - name: get Python version
        run: python -V

      - name: Build
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Install dependencies for testing 
        run: |
          python -m pip install --upgrade pip
          python -m pip install torch torchvision
          python -m pip install pytest
          python -m pip install dist/*.whl

      - name: get pip list
        run: pip list   

      - name: Run tests 
        run: |
          pytest


