
name: Build_Package

on:
  push:
    branches:
      - feat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build module
        run: python -m pip install --upgrade pip build

      - name: get the wd
        run: pwd  

      - name: get Python version
        run: python -V

      - name: Build
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Install dependencies for testing 
        run: |
          python -m pip install --upgrade pip
          python -m pip install torch torchvision
          python -m pip install pytest

      - name: Run tests 
        run: |
          pytest test/test_build_under_vev.py


